steps:
  - id: 'npm install'
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - id: "deploy firebase"
    name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      [
          "deploy",
          "--project",
          "$_FIREBASE_PROJECT_ID",
          "--only",
          "functions",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
