steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "registerCompanyOnCreateCustomer"
      - "--project"
      - "${_FIREBASE_PROJECT_ID}"
      - "--region=us-central1"
      - "--source=."
      - "--trigger-http"
      - "--runtime=nodejs14"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
